In [1]:
#PREPROCESS DATA
import Data_Preprocessing.data_preprocess_adultData as preprocess 
features, feature_types, labels= preprocess.preprocess_adult()

       10th   6        Never-married   
6      29                  ?  227026        HS-grad   9        Never-married   
7      63   Self-emp-not-inc  104626    Prof-school  15   Married-civ-spouse   
8      24            Private  369667   Some-college  10        Never-married   
9      55            Private  104996        7th-8th   4   Married-civ-spouse   
10     65            Private  184454        HS-grad   9   Married-civ-spouse   
11     36        Federal-gov  212465      Bachelors  13   Married-civ-spouse   
12     26            Private   82091        HS-grad   9        Never-married   
13     58                  ?  299831        HS-grad   9   Married-civ-spouse   
14     48            Private  279724        HS-grad   9   Married-civ-spouse   
15     43            Private  346189        Masters  14   Married-civ-spouse   
16     20          State-gov  444554   Some-college  10        Never-married   
17     43            Private  128354        HS-grad   9   Married-civ-spouse   


In [2]:
#KCROSS FOLD VALIDATION
import Models.kfold_CV_try as cv

# Train test split
xTrain_adult, xTest_adult, yTrain_adult, yTest_adult = cv.split_train_test(features, labels, 0.2)
print(yTrain_adult);print(yTest_adult)

[' <=50K.' ' >50K.' ' <=50K.' ... ' <=50K' ' <=50K.' ' >50K']
[' >50K' ' <=50K' ' <=50K' ... ' <=50K.' ' <=50K.' ' <=50K']


In [3]:
folds = 5 # delete folds later when embedded in function input
# cv_train_data_ion is xTrain_ion split into five chunks
dataset_split_in, cv_train_data_adult,cv_train_label_adult= cv.kfold_cross_validation(xTrain_adult,yTrain_adult,folds)
# print(cv_train_data_ion,cv_train_label_ion)

# the last input for cv.train_validation_split is the number of experiments you are running currently, 5 in total. 
# each experiments is organizing the five chunks from cv_train_data_ion into 4 chunks for training_data_ion and 1 chunk for validate_data_ion for cross validation, just need to uncomment the line you want to experiment currently. 

# will be in a for-loop when computing accuracy scores 
#exp1: 
validate_data_adult,validate_labels_adult,training_data_adult,training_labels_adult = cv.train_validation_split(cv_train_data_adult,cv_train_label_adult,1)

#exp2:
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,2)

#exp3:
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,3)

#exp4:
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,4)

#exp5: 
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,5)
print(validate_data_adult,validate_labels_adult)
print(validate_data_adult.shape,validate_labels_adult.shape)
print("uhhh")
print(training_data_adult)

[[25 114483 10 ... 1 0 0]
 [30 303485 10 ... 1 0 0]
 [46 117605 5 ... 1 0 0]
 ...
 [33 90409 13 ... 1 0 0]
 [37 123104 16 ... 1 0 0]
 [50 94885 13 ... 1 0 0]] [' <=50K' ' <=50K' ' <=50K' ... ' <=50K.' ' <=50K.' ' >50K']
(6873, 108) (6873,)
uhhh
[[50 229318 9 ... 0 0 0]
 [45 155093 6 ... 0 0 0]
 [26 211199 6 ... 1 0 0]
 ...
 [33 122220 10 ... 1 0 0]
 [66 163726 9 ... 1 0 0]
 [44 194924 9 ... 1 0 0]]


In [4]:
#NAIVE BAYES
import Models.naive_bayes_v2 as nb 
import numpy as np 
print(feature_types)
nbadult= nb.Naive_Bayes("Adult", "binary", feature_types)
nbparams= nbadult.fit(training_data_adult, training_labels_adult, validate_labels_adult)
print("hi")
nbresults= nbadult.predict(xTest_adult, nbparams)
print(nbresults)
print("um")

0, 1, 0, 1, 1, 0, 2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 1, 3, 2, 1, 1, 0, 0, 2, 0, 2, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 2, 0, 0, 2, 2, 2, 0, 1, 3, 2, 1, 2, 1, 0, 1, 2, 0, 0, 0, 2, 0, 3, 0, 1, 0, 0, 2, 2, 0, 1, 1, 0, 3, 0, 0, 2, 0, 0, 0, 1, 1, 1, 2, 0, 1, 2, 0, 3, 0, 0, 3, 0, 2, 3, 3, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 3, 2, 1, 0, 3, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 2, 1, 0, 0, 0, 0, 3, 1, 1, 3, 0, 1, 0, 0, 0, 2, 1, 2, 3, 0, 1, 1, 2, 0, 1, 2, 0, 0, 3, 0, 0, 0, 3, 2, 3, 0, 2, 0, 0, 1, 0, 2, 0, 1, 1, 1, 1, 2, 2, 3, 0, 0, 0, 0, 2, 1, 1, 0, 2, 0, 1, 0, 0, 0, 2, 2, 1, 2, 3, 0, 0, 2, 0, 1, 3, 1, 0, 2, 0, 0, 1, 0, 0, 1, 2, 0, 0, 1, 0, 1, 3, 1, 1, 0, 2, 1, 0, 0, 2, 2, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 1, 0, 2, 0, 1, 0, 0, 2, 0, 1, 0, 1, 3, 2, 2, 0, 0, 3, 1, 1, 3, 1, 0, 2, 0, 2, 2, 2, 0, 0, 1, 1, 2, 0, 0, 2, 3, 0, 1, 3, 1, 0, 1, 1, 2, 1, 2, 0, 0, 0, 0, 3, 0, 0, 1, 0, 1, 3, 1, 0, 0

IndexError: too many indices for array

In [ ]:
#LOGISTIC REGRESSION
import Models.logisticRegression as lr
adultlr1 = lr.Logistic_Regression(0.02,"Ionosphere","binary") # input step size
# params = ionslr1.fit(cv_train_data, cv_train_label, 0.02, 1e-1)
params = adultlr1.fit(training_data_adult,training_labels_adult,0.02,1e-1)
print(params)
results= adultlr1.predict(params, xTest_adult)
print(results)
#adding a separate comment
# input learning rate and termination conditions

In [ ]:
#ACCURACY