In [1]:
import Data_Preprocessing.data_preprocess_glass as glass
import numpy as np
import scipy
import nltk.classify.scikitlearn
#design_matrix, labels= glass.preprocess()
training_data, training_labels = glass.preprocess()
#preprocess the glass data
print("it works")


[[  1.        1.52101  13.64    ...   0.        0.        1.     ]
 [  2.        1.51761  13.89    ...   0.        0.        1.     ]
 [  3.        1.51618  13.53    ...   0.        0.        1.     ]
 ...
 [212.        1.52065  14.36    ...   1.64      0.        7.     ]
 [213.        1.51651  14.38    ...   1.57      0.        7.     ]
 [214.        1.51711  14.23    ...   1.67      0.        7.     ]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 5. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5. 5. 5. 6. 6. 6. 6. 6. 6. 6. 6. 6. 7. 7. 7. 7. 7. 7. 7.
 7. 7. 7

In [3]:
#K-Fold Validation
import Models.kfold_CV_try as cv

# Train test split
xTrain_glass, xTest_glass, yTrain_glass, yTest_glass = cv.split_train_test(training_data, training_labels, 0.2)
# print(xTest_ion); print(xTrain_ion); print(yTest_ion);print(yTrain_ion)

In [5]:
folds = 5 # delete folds later when embedded in function input
# cv_train_data_ion is xTrain_ion split into five chunks
dataset_split_in, cv_train_data_glass,cv_train_label_glass= cv.kfold_cross_validation(xTrain_glass,yTrain_glass,folds)
# print(cv_train_data_ion,cv_train_label_ion)

# the last input for cv.train_validation_split is the number of experiments you are running currently, 5 in total. 
# each experiments is organizing the five chunks from cv_train_data_ion into 4 chunks for training_data_ion and 1 chunk for validate_data_ion for cross validation, just need to uncomment the line you want to experiment currently. 

#exp1: 
validate_data_glass,validate_labels_glass,training_data_glass,training_labels_glass = cv.train_validation_split(cv_train_data_glass,cv_train_label_glass,1)

#exp2:
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,2)

#exp3:
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,3)

#exp4:
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,4)

#exp5: 
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,5)
print(validate_data_glass,validate_labels_glass)
print(validate_data_glass.shape,validate_labels_glass.shape)

[[74.0 1.51631 13.34 3.57 1.57 72.87 0.61 7.89 0.0 0.0]
 [79.0 1.51613 13.92 3.52 1.25 72.88 0.37 7.94 0.0 0.14]
 [194.0 1.51719 14.75 0.0 2.0 73.02 0.0 8.53 1.59 0.08]
 [133.0 1.51813 13.43 3.98 1.18 72.49 0.58 8.15 0.0 0.0]
 [29.0 1.51768 12.56 3.52 1.43 73.15 0.57 8.54 0.0 0.0]
 [193.0 1.51623 14.2 0.0 2.79 73.46 0.04 9.04 0.4 0.09]
 [86.0 1.51625 13.36 3.58 1.49 72.72 0.45 8.21 0.0 0.0]
 [26.0 1.51764 12.98 3.54 1.21 73.0 0.65 8.53 0.0 0.0]
 [132.0 1.52614 13.7 0.0 1.36 71.24 0.19 13.44 0.0 0.1]
 [141.0 1.5169 13.33 3.54 1.61 72.54 0.68 8.11 0.0 0.0]
 [104.0 1.52725 13.8 3.15 0.66 70.57 0.08 11.64 0.0 0.0]
 [120.0 1.51652 13.56 3.57 1.47 72.45 0.64 7.96 0.0 0.0]
 [150.0 1.51643 12.16 3.52 1.35 72.89 0.57 8.53 0.0 0.0]
 [178.0 1.51937 13.79 2.41 1.19 72.76 0.0 9.77 0.0 0.0]
 [125.0 1.52177 13.2 3.68 1.15 72.75 0.54 8.52 0.0 0.0]
 [41.0 1.51793 12.79 3.5 1.12 73.03 0.64 8.77 0.0 0.0]
 [110.0 1.51818 13.72 0.0 0.56 74.45 0.0 10.99 0.0 0.0]
 [147.0 1.51769 13.65 3.66 1.11 72.77 0.11 8.

In [6]:
import Models.naive_bayes_v2 as bayes
import numpy as np
import Models.logisticRegression as logReg 
features_types= np.array(["continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous"])
print(features_types)

#NAIVE BAYES
glass_bayes= bayes.Naive_Bayes("glass", "multiclass", features_types)
print(glass_bayes.name)
nb_results = glass_bayes.fit(training_data_glass, training_labels_glass, validate_labels_glass)
nb_test_results = glass_bayes.predict(xTest_glass, nb_results)

print("NAIVE BAYES RESULTS")
print(nb_results)
print(nb_test_results)
print(nb_results.shape)
# glass_bayes.predict()

#LINEAR REGRESSION AS BASELINE

['continuous' 'continuous' 'continuous' 'continuous' 'continuous'
 'continuous' 'continuous' 'continuous' 'continuous' 'continuous']
glass
Now fitting glass
[1, 3, 5, 1, 1, 3, 3, 5, 1, 5, 1, 5, 2, 1, 0, 1, 1, 1, 1, 4, 2, 0, 1, 0, 0, 0, 4, 1, 1, 5, 0, 0, 5, 1, 2, 1, 2, 1, 1, 0, 0, 3, 0, 0, 3, 0, 0, 0, 1, 0, 2, 0, 3, 1, 5, 0, 0, 5, 2, 1, 0, 1, 1, 4, 3, 0, 0, 3, 1, 0, 5, 1, 1, 4, 1, 0, 0, 0, 0, 1, 1, 5, 0, 0, 3, 3, 0, 5, 2, 1, 1, 4, 5, 0, 1, 1, 0, 0, 1, 5, 0, 1, 0, 1, 0, 0, 0, 3, 0, 0, 5, 2, 1, 2, 5, 0, 0, 1, 1, 5, 1, 4, 0, 1, 0, 0, 0, 1, 5, 0, 1, 1, 0, 0, 0, 5]
(136, 6)
(136, 10)
(136, 10)
(136, 6)
(6, 10)
(6, 10)
log prior
[[-1.02083459]
 [-1.15145477]
 [-2.71543031]
 [-2.51475961]
 [-3.12089542]
 [-2.02228313]]


IndexError: too many indices for array

In [7]:
import numpy as np
import Models.logisticRegression as logReg 
#LOGISTIC REGRESSION
print("LOGISTIC REGRESSION")
glass_log= logReg.Logistic_Regression(.6, "glass", "categorical")
print(glass_log.name)
log_results= glass_log.fit(training_data_glass, training_labels_glass, learning_rate=1, term=1)
log_test_results= glass_log.predict(log_results, xTest_glass)
print(log_results)
print(log_results.shape)

LOGISTIC REGRESSION
glass
Now fitting glass
[1, 3, 5, 1, 1, 3, 3, 5, 1, 5, 1, 5, 2, 1, 0, 1, 1, 1, 1, 4, 2, 0, 1, 0, 0, 0, 4, 1, 1, 5, 0, 0, 5, 1, 2, 1, 2, 1, 1, 0, 0, 3, 0, 0, 3, 0, 0, 0, 1, 0, 2, 0, 3, 1, 5, 0, 0, 5, 2, 1, 0, 1, 1, 4, 3, 0, 0, 3, 1, 0, 5, 1, 1, 4, 1, 0, 0, 0, 0, 1, 1, 5, 0, 0, 3, 3, 0, 5, 2, 1, 1, 4, 5, 0, 1, 1, 0, 0, 1, 5, 0, 1, 0, 1, 0, 0, 0, 3, 0, 0, 5, 2, 1, 2, 5, 0, 0, 1, 1, 5, 1, 4, 0, 1, 0, 0, 0, 1, 5, 0, 1, 1, 0, 0, 0, 5]
[[0, 1, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 1], [0, 1, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0], [0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 1], [0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1], [0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1], [0, 0, 1, 0, 0, 0], [0, 1, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0], [0, 0, 1, 0, 0, 0], [1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0], [0, 1,

ValueError: operands could not be broadcast together with shapes (136,) (136,6) 