In [7]:
# Import package
from urllib.request import urlretrieve

# Import pandas
import pandas as pd

# Assign url of file: url
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data'

# Save file locally
urlretrieve(url, 'ionosphere-data.csv')

# Read file into a DataFrame and print its head
df = pd.read_csv('ionosphere-data.csv', sep=',')
print(df)

1  0  0.99539  -0.05889  0.85243  0.02306  0.83398  -0.37708      1.1  \
0    1  0  1.00000  -0.18829  0.93035 -0.36156 -0.10868  -0.93597  1.00000   
1    1  0  1.00000  -0.03365  1.00000  0.00485  1.00000  -0.12062  0.88965   
2    1  0  1.00000  -0.45161  1.00000  1.00000  0.71216  -1.00000  0.00000   
3    1  0  1.00000  -0.02401  0.94140  0.06531  0.92106  -0.23255  0.77152   
4    1  0  0.02337  -0.00592 -0.09924 -0.11949 -0.00763  -0.11824  0.14706   
..  .. ..      ...       ...      ...      ...      ...       ...      ...   
345  1  0  0.83508   0.08298  0.73739 -0.14706  0.84349  -0.05567  0.90441   
346  1  0  0.95113   0.00419  0.95183 -0.02723  0.93438  -0.01920  0.94590   
347  1  0  0.94701  -0.00034  0.93207 -0.03227  0.95177  -0.03431  0.95584   
348  1  0  0.90608  -0.01657  0.98122 -0.01989  0.95691  -0.03646  0.85746   
349  1  0  0.84710   0.13533  0.73638 -0.06151  0.87873   0.08260  0.88928   

     0.03760  ...  -0.51171  0.41078  -0.46168  0.21266  -0.34090  0

In [8]:
# Import numpy
import numpy as np

# Convert to numpy
#df.to_numpy()
temp = df.values
R,C = temp.shape
#print(C)

# Split array into design matrix and labels
ionosphere_labels = temp[:, C-1]
print(ionosphere_labels)



['b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g

In [10]:
import numpy as np
# Remove labels to get design matrix
ionosphere_design_matrix= np.delete(temp, C-1, 1)
print(ionosphere_design_matrix)



[[1 0 1.0 ... -0.06287999999999999 -0.13738 -0.02447]
 [1 0 1.0 ... -0.2418 0.56045 -0.38238]
 [1 0 1.0 ... 1.0 -0.32382 1.0]
 ...
 [1 0 0.94701 ... 0.00442 0.9269700000000001 -0.00577]
 [1 0 0.9060799999999999 ... -0.03757 0.87403 -0.16243]
 [1 0 0.8471 ... -0.06677999999999999 0.85764 -0.06151]]


In [11]:
import Models.kfold_CV_try as cv

# Train test split
xTrain_ion, xTest_ion, yTrain_ion, yTest_ion = cv.split_train_test(ionosphere_design_matrix, ionosphere_labels, 0.2)

In [12]:
#CV
dataset_split_ion, cv_train_data_ion1, cv_train_label_ion1 = cv.kfold_cross_validation(xTrain_ion, yTrain_ion, 1)

cv_train_data_np1 = np.asarray(cv_train_data_ion1)
cv_train_label_np1 = np.asarray(cv_train_label_ion1)

cv_train_data = cv_train_data_np1[0, :, :]
cv_train_label = cv_train_label_np1[0, :]

print(cv_train_data.shape)
print(cv_train_label.shape)


(280, 34)
(280,)


In [13]:
import Models.logisticRegression as lr

ionslr1 = lr.Logistic_Regression(0.02,"Ionosphere","binary") # input step size
params = ionslr1.fit(cv_train_data, cv_train_label, 0.02, 1e-1)
#adding a separate comment
# input learning rate and termination conditions

Now fitting Ionosphere
0.5655794314732178
0.55047469612982
0.5358829570723745
0.5217956095938275
0.5082027719772599
0.4950935170944534
0.4824560811837572
0.4702780503384262
0.45854652563975046
0.4472482681516874
0.43636982517589695
0.42589763926740626
0.41581814154881364
0.4061178308500917
0.3967833401544068
0.38780149175854445
0.37915934246808386
0.37084422004918877
0.36284375205604685
0.35514588804954594
0.3477389161216244
0.3406114745429068
0.333752559260075
0.32715152788474544
0.3207981007378309
0.31468235944255585
0.30879474349535946
0.30312604518658137
0.2976674031917208
0.29241029510874456
0.2873465291769527
0.2824682353777957
0.2777678560873252
0.2732381364232039
0.2688721144059666
0.2646631110341272
0.2606047203554084
0.2566907996014822
0.2529154594408768
0.24927305439383712
0.2457581734436941
0.24236563087148227
0.2390904573339659
0.235927891199698
0.23287337015314058
0.22992252307303673
0.2270711621880788
0.2243152755103348
0.2216510195448005
0.2190747122717711
0.21658282639