In [9]:
# Import package
from urllib.request import urlretrieve

# Import pandas
import pandas as pd

# Assign url of file: url
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data'

# Save file locally
urlretrieve(url, 'ionosphere-data.csv')

# Read file into a DataFrame and print its head
df = pd.read_csv('ionosphere-data.csv', sep=',')
print(df)

1  0  0.99539  -0.05889  0.85243  0.02306  0.83398  -0.37708      1.1  \
0    1  0  1.00000  -0.18829  0.93035 -0.36156 -0.10868  -0.93597  1.00000   
1    1  0  1.00000  -0.03365  1.00000  0.00485  1.00000  -0.12062  0.88965   
2    1  0  1.00000  -0.45161  1.00000  1.00000  0.71216  -1.00000  0.00000   
3    1  0  1.00000  -0.02401  0.94140  0.06531  0.92106  -0.23255  0.77152   
4    1  0  0.02337  -0.00592 -0.09924 -0.11949 -0.00763  -0.11824  0.14706   
..  .. ..      ...       ...      ...      ...      ...       ...      ...   
345  1  0  0.83508   0.08298  0.73739 -0.14706  0.84349  -0.05567  0.90441   
346  1  0  0.95113   0.00419  0.95183 -0.02723  0.93438  -0.01920  0.94590   
347  1  0  0.94701  -0.00034  0.93207 -0.03227  0.95177  -0.03431  0.95584   
348  1  0  0.90608  -0.01657  0.98122 -0.01989  0.95691  -0.03646  0.85746   
349  1  0  0.84710   0.13533  0.73638 -0.06151  0.87873   0.08260  0.88928   

     0.03760  ...  -0.51171  0.41078  -0.46168  0.21266  -0.34090  0

In [10]:
# Import numpy
import numpy as np

# Convert to numpy
#df.to_numpy()
temp = df.values
R,C = temp.shape
#print(C)

# Split array into design matrix and labels
ionosphere_labels = temp[:, C-1]
print(ionosphere_labels)



['b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g

In [11]:
import numpy as np
# Remove labels to get design matrix
ionosphere_design_matrix= np.delete(temp, C-1, 1)
print(ionosphere_design_matrix)



[[1 0 1.0 ... -0.06287999999999999 -0.13738 -0.02447]
 [1 0 1.0 ... -0.2418 0.56045 -0.38238]
 [1 0 1.0 ... 1.0 -0.32382 1.0]
 ...
 [1 0 0.94701 ... 0.00442 0.9269700000000001 -0.00577]
 [1 0 0.9060799999999999 ... -0.03757 0.87403 -0.16243]
 [1 0 0.8471 ... -0.06677999999999999 0.85764 -0.06151]]


In [12]:
import Models.kfold_CV_try as cv

# Train test split
xTrain_ion, xTest_ion, yTrain_ion, yTest_ion = cv.split_train_test(ionosphere_design_matrix, ionosphere_labels, 0.2)
# print(xTest_ion); print(xTrain_ion); print(yTest_ion);print(yTrain_ion)


In [13]:
folds = 5 # delete folds later when embedded in function input
# cv_train_data_ion is xTrain_ion split into five chunks
dataset_split_in, cv_train_data_ion,cv_train_label_ion= cv.kfold_cross_validation(xTrain_ion,yTrain_ion,folds)
# print(cv_train_data_ion,cv_train_label_ion)

# the last input for cv.train_validation_split is the number of experiments you are running currently, 5 in total. 
# each experiments is organizing the five chunks from cv_train_data_ion into 4 chunks for training_data_ion and 1 chunk for validate_data_ion for cross validation, just need to uncomment the line you want to experiment currently. 

#exp1: 
validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,1)

#exp2:
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,2)

#exp3:
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,3)

#exp4:
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,4)

#exp5: 
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,5)
print(validate_data_ion,validate_labels_ion)
print(validate_data_ion.shape,validate_labels_ion.shape)

[[1 0 0.85736 ... -0.01942 0.79089 -0.09186]
 [1 0 0.7408399999999999 ... 0.14697000000000002 0.57455 0.15114]
 [1 0 0.6381600000000001 ... -1.0 1.0 1.0]
 ...
 [1 0 0.5 ... 0.14783 0.44783 0.17390999999999998]
 [1 0 0.62745 ... -0.21569000000000002 0.47058999999999995 -0.27451]
 [1 0 0.8628399999999999 ... -0.19923 -0.42912 -0.31954]] ['g' 'g' 'b' 'g' 'b' 'b' 'g' 'g' 'g' 'g' 'b' 'g' 'g' 'b' 'g' 'g' 'g' 'g'
 'b' 'g' 'b' 'g' 'g' 'b' 'g' 'g' 'b' 'g' 'g' 'g' 'g' 'g' 'g' 'g' 'b' 'b'
 'b' 'b' 'g' 'g' 'b' 'g' 'g' 'g' 'g' 'b' 'g' 'g' 'g' 'g' 'b' 'b' 'g' 'g'
 'b' 'g']
(56, 34) (56,)


In [14]:
import Models.logisticRegression as lr

ionslr1 = lr.Logistic_Regression(0.02,"Ionosphere","binary") # input step size
# params = ionslr1.fit(cv_train_data, cv_train_label, 0.02, 1e-1)
params1 = ionslr1.fit(training_data_ion,training_labels_ion,0.02,1e-1)
#adding a separate comment
# input learning rate and termination conditions

Now fitting Ionosphere
0.5540439593553605
0.5398644961856559
0.5261578395909225
0.5129160180410959
0.5001299624111436
0.48778970231618707
0.4758845434944191
0.4644032266824028
0.45333406874225207
0.4426650870226298
0.43238410808091665
0.42247886197669465
0.41293706337986374
0.40374648073166425
0.3948949946632846
0.38637064682278305
0.3781616801932988
0.3702565719093426
0.36264405949744327
0.3553131613857998
0.34825319244717284
0.341453775261756
0.3349048477133374
0.3285966674634302
0.3225198137846259
0.3166651871763485
0.31102400713345174
0.3055878083905392
0.30034843592224625
0.2952980389417163
0.2904290641057729
0.28573424810550757
0.28120660979479023
0.27683944198624616
0.2726263030241877
0.26856100822653095
0.2646376212725896
0.2608504456005446
0.2571940158671047
0.25366308951217953
0.2502526384630876
0.24695784100573528
0.2437740738441848
0.24069690436492264
0.23772208311784168
0.23484553652233264
0.23206335980386375
0.2293718101639179
0.22676730018408559
0.22424639146341707
0.221

In [15]:
# Making LR prediction on the validatoin set
#print(validate_data_ion,validate_labels_ion)
#predictions1 = ionslr1.predict(ionslr1,params1,validate_data_ion)

predictions1 = ionslr1.predict(params1,validate_data_ion)
print(predictions1)

[ True  True  True  True  True  True  True  True  True  True False  True
  True False  True  True  True  True  True  True  True  True  True False
  True  True  True  True  True  True  True  True  True  True False False
  True  True  True  True  True  True  True  True  True False  True  True
  True  True  True False  True  True  True  True]


In [16]:
#NAIVE BAYES
import numpy as np
import Models.naive_bayes_v2 as nb 

feature_types= np.array(["continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous"])
ionnb= nb.Naive_Bayes("ionosphere", "binary", feature_types)
parameters= ionnb.fit(training_data_ion, training_labels_ion, validate_labels_ion)
results= ionnb.predict(xTest_ion, parameters)


Now fitting ionosphere
[1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1]
(224, 2)
(224, 34)
(224, 34)
(224, 2)
(2, 34)
(2, 34)
log prior
[[-1.0049268 ]
 [-0.45581899]]


IndexError: too many indices for array