In [3]:
# Import package
from urllib.request import urlretrieve

# Import pandas
import pandas as pd

# Assign url of file: url
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data'

# Save file locally
urlretrieve(url, 'ionosphere-data.csv')

# Read file into a DataFrame and print its head
df = pd.read_csv('ionosphere-data.csv', sep=',')
print(df)

1  0  0.99539  -0.05889  0.85243  0.02306  0.83398  -0.37708      1.1  \
0    1  0  1.00000  -0.18829  0.93035 -0.36156 -0.10868  -0.93597  1.00000   
1    1  0  1.00000  -0.03365  1.00000  0.00485  1.00000  -0.12062  0.88965   
2    1  0  1.00000  -0.45161  1.00000  1.00000  0.71216  -1.00000  0.00000   
3    1  0  1.00000  -0.02401  0.94140  0.06531  0.92106  -0.23255  0.77152   
4    1  0  0.02337  -0.00592 -0.09924 -0.11949 -0.00763  -0.11824  0.14706   
5    1  0  0.97588  -0.10602  0.94601 -0.20800  0.92806  -0.28350  0.85996   
6    0  0  0.00000   0.00000  0.00000  0.00000  1.00000  -1.00000  0.00000   
7    1  0  0.96355  -0.07198  1.00000 -0.14333  1.00000  -0.21313  1.00000   
8    1  0 -0.01864  -0.08459  0.00000  0.00000  0.00000   0.00000  0.11470   
9    1  0  1.00000   0.06655  1.00000 -0.18388  1.00000  -0.27320  1.00000   
10   1  0  1.00000  -0.54210  1.00000 -1.00000  1.00000  -1.00000  1.00000   
11   1  0  1.00000  -0.16316  1.00000 -0.10169  0.99999  -0.15197  1.

In [4]:
# Import numpy
import numpy as np

# Convert to numpy
#df.to_numpy()
temp = df.values
R,C = temp.shape
#print(C)

# Split array into design matrix and labels
ionosphere_labels = temp[:, C-1]
print(ionosphere_labels)



['b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g

In [54]:
import numpy as np
# Remove labels to get design matrix
ionosphere_design_matrix= np.delete(temp, C-1, 1)
print(ionosphere_design_matrix)



[[1 0 1.0 ... -0.06287999999999999 -0.13738 -0.02447]
 [1 0 1.0 ... -0.2418 0.56045 -0.38238]
 [1 0 1.0 ... 1.0 -0.32382 1.0]
 ...
 [1 0 0.94701 ... 0.00442 0.9269700000000001 -0.00577]
 [1 0 0.9060799999999999 ... -0.03757 0.87403 -0.16243]
 [1 0 0.8471 ... -0.06677999999999999 0.85764 -0.06151]]


In [58]:
import Models.kfold_CV_try as cv

# Train test split
xTrain_ion, xTest_ion, yTrain_ion, yTest_ion = cv.split_train_test(ionosphere_design_matrix, ionosphere_labels, 0.2)
# print(xTest_ion); print(xTrain_ion); print(yTest_ion);print(yTrain_ion)
# change the binary label 'g' and 'b' into 1 and 0
for i in enumerate(yTrain_ion):
    if i[1] == 'g':
        yTrain_ion[i[0]] = 1
    elif i[1] == 'b':
        yTrain_ion[i[0]] = 0
yTrain_ion=yTrain_ion.astype('int')
for i in enumerate(yTest_ion):
    if i[1] == 'g':
        yTest_ion[i[0]] = 1
    elif i[1] == 'b':
        yTest_ion[i[0]] = 0        
yTest_ion=yTest_ion.astype('int')

print(yTrain_ion);print(yTest_ion)

[1 0 1 1 0 1 1 1 1 0 0 0 1 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1
 0 1 1 1 0 1 0 0 1 1 1 1 0 1 1 1 1 1 0 1 0 1 0 1 1 0 1 1 0 1 1 1 0 1 1 1 1
 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 0 0 0 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1
 1 1 1 1 0 0 1 0 1 1 0 1 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 0 0 0 0
 1 1 1 1 1 0 1 1 1 1 1 0 1 0 1 1 1 0 0 0 1 0 1 0 0 0 0 1 1 1 1 1 0 1 1 0 1
 1 1 0 1 1 0 0 1 1 1 1 0 1 1 1 0 1 0 0 0 1 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1
 1 1 1 0 0 1 1 0 1 1 1 1 0 0 0 0 1 1 1 0 0 0 1 1 1 0 1 1 0 0 0 0 0 1 0 1 0
 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0 1 1 0 1 1]
[0 0 1 1 1 0 0 1 0 1 1 0 0 1 0 1 0 1 1 1 1 1 1 0 1 0 1 1 0 0 0 0 0 1 1 1 1
 1 0 0 1 0 1 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 0 1 1 1 0 0 1 1 1 1 0 1]


In [59]:
folds = 5 # delete folds later when embedded in function input
# cv_train_data_ion is xTrain_ion split into five chunks
dataset_split_in, cv_train_data_ion,cv_train_label_ion= cv.kfold_cross_validation(xTrain_ion,yTrain_ion,folds)
# print(cv_train_data_ion,cv_train_label_ion)

# the last input for cv.train_validation_split is the number of experiments you are running currently, 5 in total. 
# each experiments is organizing the five chunks from cv_train_data_ion into 4 chunks for training_data_ion and 1 chunk for validate_data_ion for cross validation, just need to uncomment the line you want to experiment currently. 

# will be in a for-loop when computing accuracy scores 
#exp1: 
validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,1)

#exp2:
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,2)

#exp3:
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,3)

#exp4:
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,4)

#exp5: 
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,5)
print(validate_data_ion,validate_labels_ion)
print(validate_data_ion.shape,validate_labels_ion.shape)

[[1 0 0.08696 ... -0.07322999999999999 0.1167 -0.06865]
 [1 0 0.058660000000000004 ... 0.0 0.04749 -0.03352]
 [1 0 0.59887 ... -0.31262 0.6742 -0.22034]
 ...
 [0 0 1.0 ... -1.0 -1.0 -1.0]
 [1 0 0.47336999999999996 ... -0.14497000000000002 0.34615 -0.00296]
 [1 0 1.0 ... 0.21378000000000003 0.18086 0.19083]] [0 0 1 0 0 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 0 1 0 1 1 0 0 0 0 0 0
 1 1 0 1 1 0 1 1 1 1 0 0 0 0 1 1 0 1 1]
(56, 34) (56,)


In [60]:
import Models.logisticRegression as lr

ionslr1 = lr.Logistic_Regression(0.02,"Ionosphere","binary") # input step size
# params = ionslr1.fit(cv_train_data, cv_train_label, 0.02, 1e-1)
params1 = ionslr1.fit(training_data_ion,training_labels_ion,0.02,1e-1)
#adding a separate comment
# input learning rate and termination conditions

Now fitting Ionosphere
0.6139772778421112
0.5976139123162385
0.5818065165072646
0.5665471347608791
0.5518260786030147
0.5376322266397486
0.5239532964335114
0.5107760884187924
0.49808670261060606
0.4858707293609807
0.474113415762071
0.4627998095078268
0.45191488213578646
0.4414436335999341
0.4313711800947837
0.4216828269768058
0.4123641285257698
0.4034009361665084
0.3947794366395992
0.38648618147397534
0.37850810898031223
0.37083255985455427
0.36344728735846293
0.35634046292995725
0.3495006779710835
0.34291694246594034
0.3365786809947306
0.33047572663297686
0.3245983131563437
0.31893706591085963
0.31348299165498245
0.3082274676332526
0.30316223010056886
0.29827936248078046
0.29357128331272064
0.2890307341104679
0.2846507672419984
0.28042473391103734
0.2763462723104087
0.2724092960011613
0.26860798255986756
0.26493676252649156
0.2613903086768058
0.25796352563632
0.25465153984684014
0.2514496898919516
0.2483535171837555
0.24535875700996193
0.24246132993783662
0.2396573335694233
0.23694303

In [68]:
# %% Making LR prediction on the validatoin set

# need to convert predictions into 1 or 0

# pred_vali1 is a boolean array, pred_vali*1 gives binary 1 or 0 automatically 
pred_vali = ionslr1.predict(params1,validate_data_ion)
pred_vali=pred_vali * 1

print(pred_vali)
print(validate_labels_ion)


[1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 0 1 1]
[0 0 1 0 0 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 0 1 0 1 1 0 0 0 0 0 0
 1 1 0 1 1 0 1 1 1 1 0 0 0 0 1 1 0 1 1]


In [69]:
# try prediction for testing set 
# print(xTest_ion); print(yTest_ion)
pred_test = ionslr1.predict(params1,xTest_ion)
# change boolean into 1 or 0
pred_test = pred_test * 1
print(pred_test)


[0 0 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 0 1 1 1 0 1 0 0 1 1 1 1
 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1]


In [71]:

# %% Using evaluate_acc to do 5-fold CV

# LOGISTIC REGRESSION MODEL 
# APPEND SCORES
vali_acc_score_lr=[]; vali_preci_socre_lr=[]; vali_recall_score_lr=[];vali_f1_score_lr=[]
# implement LR model 
import Models.logisticRegression as lr
import Models.evaluate_acc as acc
# LogReg1 =LogisticRegression()

for i in range(5):
    validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,i+1)
    training_data_ion=training_data_ion.astype('int'); training_labels_ion=training_labels_ion.astype('int')
    validate_data_ion=validate_data_ion.astype('int'); validate_labels_ion=validate_labels_ion.astype('int')
    
    # delete the previous loop's model 
    # if i > 0:
    #    del LogReg1
 
    ionslr1 = lr.Logistic_Regression(0.02,"Ionosphere","binary")                # build model
    params1 = ionslr1.fit(training_data_ion,training_labels_ion,0.02,1e-1)      # find parameters to predict 
    validate_pred_lr= ionslr1.predict(params1,validate_data_ion)                # predict on validation data 
    validate_pred_lr=validate_pred_lr * 1                                       # change True of False from validate_pred_lr into binary 
    
    # accuracy score 
    validate_expect_lr = validate_labels_ion
    tp, tn, fn, fp = acc.compute_tp_tn_fn_fp(validate_expect_lr,validate_pred_lr) # for other score computation 
    conf_mat = acc.compute_tp_tn_fn_fp(validate_expect_lr,validate_pred_lr)     # confusion matrix: (tp, tn, fn, fp)
    validate_acc_score_lr = (acc.compute_accuracy(*list(conf_mat)))*0.01        # compute accuracy score   
    vali_acc_score_lr.append(validate_acc_score_lr)                             # append validation accuracy score for each experiment 
    
    # precision score 
    validate_preci_score_lr = acc.compute_precision(tp, fp)*0.01
    vali_preci_socre_lr.append(validate_preci_score_lr)    

    # recall score 
    validate_recall_score_lr = acc.compute_recall(tp, fn)*0.01
    vali_recall_score_lr.append(validate_recall_score_lr)
    
    # f1 score 
    validate_f1_score_lr = acc.compute_f1_score(validate_expect_lr,validate_pred_lr)
    vali_f1_score_lr.append(validate_f1_score_lr)
    


mu_vali_acc_lr=np.mean(vali_acc_score_lr); 
mu_vali_preci_lr=np.mean(vali_preci_socre_lr); 
mu_vali_recall_lr=np.mean(vali_recall_score_lr);
mu_vali_f1_lr=np.mean(vali_f1_score_lr)
print('LR accuracy score:',mu_vali_acc_lr)
print('LR precision score:',mu_vali_preci_lr)
print('LR recall score:',mu_vali_recall_lr)
print('LR f1 score:',mu_vali_f1_lr)



384947
0.11332625892036158
0.11310916630402876
0.11289307394934439
0.11267797475080919
0.1124638616721036
0.11225072774527053
0.11203856606990936
0.11182736981237903
0.1116171322050119
0.11140784654533795
0.11119950619531771
0.11099210458058618
0.11078563518970568
0.1105800915734283
0.11037546734396772
0.11017175617428045
0.10996895179735618
0.10976704800551688
0.10956603864972514
0.10936591763890115
0.10916667893924839
0.1089683165735881
0.10877082462070162
0.10857419721468183
0.10837842854429235
0.1081835128523351
0.1079894444350258
0.10779621764137728
0.10760382687259133
0.10741226658145704
0.10722153127175786
0.10703161549768589
0.10684251386326328
0.10665422102177156
0.1064667316751876
0.10628004057362708
0.10609414251479515
0.10590903234344383
0.10572470495083622
0.10554115527421762
0.10535837829629373
0.10517636904471461
0.10499512259156606
0.10481463405286703
0.10463489858807319
0.10445591139958743
0.10427766773227573
0.10410016287299004
0.10392339215009645
0.10374735093300977
