In [4]:
# Import package
from urllib.request import urlretrieve

# Import pandas
import pandas as pd

# Assign url of file: url
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data'

# Save file locally
urlretrieve(url, 'ionosphere-data.csv')

# Read file into a DataFrame and print its head
df = pd.read_csv('ionosphere-data.csv', sep=',')
print(df)

1  0  0.99539  -0.05889  0.85243  0.02306  0.83398  -0.37708      1.1  \
0    1  0  1.00000  -0.18829  0.93035 -0.36156 -0.10868  -0.93597  1.00000   
1    1  0  1.00000  -0.03365  1.00000  0.00485  1.00000  -0.12062  0.88965   
2    1  0  1.00000  -0.45161  1.00000  1.00000  0.71216  -1.00000  0.00000   
3    1  0  1.00000  -0.02401  0.94140  0.06531  0.92106  -0.23255  0.77152   
4    1  0  0.02337  -0.00592 -0.09924 -0.11949 -0.00763  -0.11824  0.14706   
5    1  0  0.97588  -0.10602  0.94601 -0.20800  0.92806  -0.28350  0.85996   
6    0  0  0.00000   0.00000  0.00000  0.00000  1.00000  -1.00000  0.00000   
7    1  0  0.96355  -0.07198  1.00000 -0.14333  1.00000  -0.21313  1.00000   
8    1  0 -0.01864  -0.08459  0.00000  0.00000  0.00000   0.00000  0.11470   
9    1  0  1.00000   0.06655  1.00000 -0.18388  1.00000  -0.27320  1.00000   
10   1  0  1.00000  -0.54210  1.00000 -1.00000  1.00000  -1.00000  1.00000   
11   1  0  1.00000  -0.16316  1.00000 -0.10169  0.99999  -0.15197  1.

In [5]:
# Import numpy
import numpy as np

# Convert to numpy
#df.to_numpy()
temp = df.values
R,C = temp.shape
#print(C)

# Split array into design matrix and labels
ionosphere_labels = temp[:, C-1]
print(ionosphere_labels)



['b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g

In [6]:
import numpy as np
# Remove labels to get design matrix
ionosphere_design_matrix= np.delete(temp, C-1, 1)
print(ionosphere_design_matrix)



[[1 0 1.0 ... -0.06287999999999999 -0.13738 -0.02447]
 [1 0 1.0 ... -0.2418 0.56045 -0.38238]
 [1 0 1.0 ... 1.0 -0.32382 1.0]
 ...
 [1 0 0.94701 ... 0.00442 0.9269700000000001 -0.00577]
 [1 0 0.9060799999999999 ... -0.03757 0.87403 -0.16243]
 [1 0 0.8471 ... -0.06677999999999999 0.85764 -0.06151]]


In [7]:
import Models.kfold_CV_try as cv

# Train test split
xTrain_ion, xTest_ion, yTrain_ion, yTest_ion = cv.split_train_test(ionosphere_design_matrix, ionosphere_labels, 0.2)
# print(xTest_ion); print(xTrain_ion); print(yTest_ion);print(yTrain_ion)
# change the binary label 'g' and 'b' into 1 and 0
for i in enumerate(yTrain_ion):
    if i[1] == 'g':
        yTrain_ion[i[0]] = 1
    elif i[1] == 'b':
        yTrain_ion[i[0]] = 0
yTrain_ion=yTrain_ion.astype('int')
for i in enumerate(yTest_ion):
    if i[1] == 'g':
        yTest_ion[i[0]] = 1
    elif i[1] == 'b':
        yTest_ion[i[0]] = 0        
yTest_ion=yTest_ion.astype('int')

print(yTrain_ion);print(yTest_ion)

[1 0 1 1 0 1 1 1 1 0 0 0 1 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1
 0 1 1 1 0 1 0 0 1 1 1 1 0 1 1 1 1 1 0 1 0 1 0 1 1 0 1 1 0 1 1 1 0 1 1 1 1
 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 0 0 0 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1
 1 1 1 1 0 0 1 0 1 1 0 1 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 0 0 0 0
 1 1 1 1 1 0 1 1 1 1 1 0 1 0 1 1 1 0 0 0 1 0 1 0 0 0 0 1 1 1 1 1 0 1 1 0 1
 1 1 0 1 1 0 0 1 1 1 1 0 1 1 1 0 1 0 0 0 1 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1
 1 1 1 0 0 1 1 0 1 1 1 1 0 0 0 0 1 1 1 0 0 0 1 1 1 0 1 1 0 0 0 0 0 1 0 1 0
 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0 1 1 0 1 1]
[0 0 1 1 1 0 0 1 0 1 1 0 0 1 0 1 0 1 1 1 1 1 1 0 1 0 1 1 0 0 0 0 0 1 1 1 1
 1 0 0 1 0 1 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 0 1 1 1 0 0 1 1 1 1 0 1]


In [8]:
folds = 5 # delete folds later when embedded in function input
# cv_train_data_ion is xTrain_ion split into five chunks
dataset_split_in, cv_train_data_ion,cv_train_label_ion= cv.kfold_cross_validation(xTrain_ion,yTrain_ion,folds)
# print(cv_train_data_ion,cv_train_label_ion)

# the last input for cv.train_validation_split is the number of experiments you are running currently, 5 in total. 
# each experiments is organizing the five chunks from cv_train_data_ion into 4 chunks for training_data_ion and 1 chunk for validate_data_ion for cross validation, just need to uncomment the line you want to experiment currently. 

# will be in a for-loop when computing accuracy scores 
#exp1: 
validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,1)

#exp2:
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,2)

#exp3:
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,3)

#exp4:
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,4)

#exp5: 
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,5)
print(validate_data_ion,validate_labels_ion)
print(validate_data_ion.shape,validate_labels_ion.shape)

[[1 0 0.6351 ... 0.19841 0.69053 0.36721]
 [1 0 0.31034 ... -0.00011999999999999999 -8e-05 -5.9999999999999995e-05]
 [1 0 0.5984 ... 0.81007 0.81979 0.6882199999999999]
 ...
 [1 0 0.0 ... 1.0 0.0 0.0]
 [1 0 1.0 ... 1.0 -1.0 1.0]
 [1 0 0.5 ... 0.14783 0.44783 0.17390999999999998]] [1 1 0 1 1 1 0 0 0 1 0 0 1 1 1 1 0 0 1 1 0 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1
 1 1 1 0 0 1 1 1 1 1 1 0 0 1 0 0 0 0 1]
(56, 34) (56,)


In [10]:
import Models.logisticRegression as lr

ionslr1 = lr.Logistic_Regression(0.02,"Ionosphere","binary") # input step size
# params = ionslr1.fit(cv_train_data, cv_train_label, 0.02, 1e-1)
params1 = ionslr1.fit(training_data_ion,training_labels_ion,0.02,1e-1)
#adding a separate comment
# input learning rate and termination conditions

Now fitting Ionosphere
0.5912739580935384
0.5758787500880542
0.5610043835223915
0.546642430428586
0.5327830586228288
0.5194152831105053
0.5065271931510879
0.4941061553866964
0.48213899392048576
0.47061214857400224
0.4595118127794129
0.44882405269490444
0.43853490918932336
0.4286304843426618
0.4190970140670121
0.409920928380467
0.40108890077406384
0.3925878880072637
0.38440516155671545
0.37652833183088913
0.3689453661529638
0.3616446014085338
0.3546147521548654
0.34784491489558234
0.3413245691392797
0.33504357578283417
0.3289921732899744
0.3231609720727332
0.3175409474273084
0.31212343132615405
0.30690010332428974
0.3018629807993263
0.29700440871106537
0.2923170490372254
0.2877938700164056
0.2834281353074151
0.2792133931551255
0.2751434656367207
0.27121243804827094
0.267414648479648
0.26374467761568654
0.2601973387929064
0.2567676683338811
0.25345091617524707
0.25024253680026154
0.2471381804825815
0.24413368484443107
0.24122506672945151
0.23840851438817795
0.2356803799722041
0.233037172

In [11]:
# %% Making LR prediction on the validatoin set

# need to convert predictions into 1 or 0

# pred_vali1 is a boolean array, pred_vali*1 gives binary 1 or 0 automatically 
pred_vali = ionslr1.predict(params1,validate_data_ion)
pred_vali=pred_vali * 1

print(pred_vali)
print(validate_labels_ion)


[1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1]
[1 1 0 1 1 1 0 0 0 1 0 0 1 1 1 1 0 0 1 1 0 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1
 1 1 1 0 0 1 1 1 1 1 1 0 0 1 0 0 0 0 1]


In [12]:
# try prediction for testing set 
# print(xTest_ion); print(yTest_ion)
pred_test = ionslr1.predict(params1,xTest_ion)
# change boolean into 1 or 0
pred_test = pred_test * 1
print(pred_test)


[0 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 0 1 0 0 1 1 1 1
 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1]


In [13]:

# %% Using evaluate_acc to do 5-fold CV

# LOGISTIC REGRESSION MODEL 
# APPEND SCORES
vali_acc_score_lr=[]; vali_preci_socre_lr=[]; vali_recall_score_lr=[];vali_f1_score_lr=[]
# implement LR model 
import Models.logisticRegression as lr
import Models.evaluate_acc as acc
# LogReg1 =LogisticRegression()

for i in range(5):
    validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,i+1)
    training_data_ion=training_data_ion.astype('int'); training_labels_ion=training_labels_ion.astype('int')
    validate_data_ion=validate_data_ion.astype('int'); validate_labels_ion=validate_labels_ion.astype('int')
    
    # delete the previous loop's model 
    # if i > 0:
    #    del LogReg1
 
    ionslr1 = lr.Logistic_Regression(0.02,"Ionosphere","binary")                # build model
    params1 = ionslr1.fit(training_data_ion,training_labels_ion,0.02,1e-1)      # find parameters to predict 
    validate_pred_lr= ionslr1.predict(params1,validate_data_ion)                # predict on validation data 
    validate_pred_lr=validate_pred_lr * 1                                       # change True of False from validate_pred_lr into binary 
    
    # accuracy score 
    validate_expect_lr = validate_labels_ion
    tp, tn, fn, fp = acc.compute_tp_tn_fn_fp(validate_expect_lr,validate_pred_lr) # for other score computation 
    conf_mat = acc.compute_tp_tn_fn_fp(validate_expect_lr,validate_pred_lr)     # confusion matrix: (tp, tn, fn, fp)
    validate_acc_score_lr = (acc.compute_accuracy(*list(conf_mat)))*0.01        # compute accuracy score   
    vali_acc_score_lr.append(validate_acc_score_lr)                             # append validation accuracy score for each experiment 
    
    # precision score 
    validate_preci_score_lr = acc.compute_precision(tp, fp)*0.01
    vali_preci_socre_lr.append(validate_preci_score_lr)    

    # recall score 
    validate_recall_score_lr = acc.compute_recall(tp, fn)*0.01
    vali_recall_score_lr.append(validate_recall_score_lr)
    
    # f1 score 
    validate_f1_score_lr = acc.compute_f1_score(validate_expect_lr,validate_pred_lr)
    vali_f1_score_lr.append(validate_f1_score_lr)
    


mu_vali_acc_lr=np.mean(vali_acc_score_lr); 
mu_vali_preci_lr=np.mean(vali_preci_socre_lr); 
mu_vali_recall_lr=np.mean(vali_recall_score_lr);
mu_vali_f1_lr=np.mean(vali_f1_score_lr)
print('LR accuracy score:',mu_vali_acc_lr)
print('LR precision score:',mu_vali_preci_lr)
print('LR recall score:',mu_vali_recall_lr)
print('LR f1 score:',mu_vali_f1_lr)



0137
0.10700368284348377
0.10679756754012915
0.10659232012436075
0.10638793587738854
0.10618441011123934
0.10598173816848974
0.10577991542200252
0.10557893727466613
0.1053787991591374
0.105179496537587
0.10498102490144814
0.1047833797711682
0.10458655669596324
0.10439055125357548
0.1041953590500335
0.10400097571941529
0.10380739692361414
0.10361461835210724
0.10342263572172651
0.10323144477643313
0.10304104128709352
0.1028514210512585
0.102662579892945
0.1024745136624201
0.10228721823598737
0.10210068951577621
0.10191492342953294
0.10172991593041468
0.10154566299678526
0.10136216063201367
0.10117940486427468
0.10099739174635167
0.10081611735544152
0.1006355777929621
0.10045576918436123
0.10027668767892856
0.10009832944960861
0.09992069069281681
Now fitting Ionosphere
0.21517903452825093
0.21440401599672468
0.21363394445687092
0.2128687810457747
0.2121084871362315
0.21135302433950606
0.2106023545079146
0.2098564397372342
0.20911524236894524
0.20837872499231153
0.2076468504463046
0.20691

In [15]:
# QUESTION 3 PART 2
# For task 3-2, CV is required to get the averaged training/validation accuracy for each learning rate (based on your choice). 
# After that, you can select the learning rate with the highest e.g. validation accuracy 
# and plot the train/validation acc - iteration figure using that best learning rate.
# When plotting, you can either plot figures on all k-folds training-validation split (k training acc -iteration figure, k val acc - iteration figure) 
# OR you can just plot figures on a selected training-validation split of your choice (1 training acc - iteration figure, 1 val acc - iteration figure). 
# The former can be seen as a bonus.
import numpy as np
import Models.kfold_CV_try as cv

learningRate=np.linspace(0.001,5,500); 
acc_learningRate=[]

for j in enumerate(learningRate):
    lRate = j[1]
    vali_acc_score_lr=[]
    for i in range(5):
        validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,i+1)
#        training_data_ion=training_data_ion.astype('int'); training_labels_ion=training_labels_ion.astype('int')
#        validate_data_ion=validate_data_ion.astype('int'); validate_labels_ion=validate_labels_ion.astype('int')
        
        ionslr1 = lr.Logistic_Regression(0.02,"Ionosphere","binary")                # build model
        params1 = ionslr1.fit(training_data_ion,training_labels_ion,lRate,1e-1)      # find parameters to predict 
        validate_pred_lr= ionslr1.predict(params1,validate_data_ion)                # predict on validation data 
        validate_pred_lr=validate_pred_lr * 1                                       # change True of False from validate_pred_lr into binary 
        
        # accuracy score 
        validate_expect_lr = validate_labels_ion
        tp, tn, fn, fp = acc.compute_tp_tn_fn_fp(validate_expect_lr,validate_pred_lr) # for other score computation 
        conf_mat = acc.compute_tp_tn_fn_fp(validate_expect_lr,validate_pred_lr)     # confusion matrix: (tp, tn, fn, fp)
        validate_acc_score_lr = (acc.compute_accuracy(*list(conf_mat)))*0.01        # compute accuracy score   
        vali_acc_score_lr.append(validate_acc_score_lr)                             # append validation accuracy score for each experiment 

    mu_vali_acc_lr=np.mean(vali_acc_score_lr); 
    acc_learningRate.append(mu_vali_acc_lr)
    
max_ionAcc = np.max(acc_learningRate)
max_lRate = learningRate[acc_learningRate.index(max_ionAcc)]  # Find the x value corresponding to the maximum y value

print('max acc score is ', max_ionAcc, 'at learning rate',max_lRate )


990667044
0.11398343482676508
0.11397351276566005
0.11396359372170801
0.11395367769326308
0.11394376467868067
0.11393385467631749
0.11392394768453185
0.11391404370168327
0.11390414272613279
0.11389424475624274
0.11388434979037676
0.11387445782689999
0.11386456886417892
0.11385468290058133
0.11384479993447649
0.1138349199642349
0.11382504298822863
0.11381516900483082
0.11380529801241622
0.11379543000936083
0.11378556499404215
0.11377570296483878
0.11376584392013088
0.1137559878582999
0.11374613477772866
0.1137362846768013
0.1137264375539033
0.11371659340742153
0.11370675223574421
0.11369691403726091
0.11368707881036245
0.11367724655344105
0.1136674172648903
0.11365759094310507
0.11364776758648167
0.11363794719341755
0.11362812976231168
0.11361831529156433
0.11360850377957699
0.11359869522475251
0.11358888962549518
0.11357908698021055
0.11356928728730535
0.11355949054518794
0.1135496967522676
0.11353990590695523
0.11353011800766305
0.11352033305280433
0.113510551040794
0.1135007719700479

In [20]:
import Models.naive_bayes_v2 as nb 
import numpy as np 
feature_types= np.array(["continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous","continuous",])

ionnb= nb.Naive_Bayes("ionosphere", "binary", feature_types)
parameters= ionnb.fit(training_data_ion, training_labels_ion, validate_data_ion)
results= ionnb.predict(xTest_ion, parameters)



Now fitting ionosphere
[1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0]
(224, 2)
(224, 34)
(224, 34)
(224, 2)
(2, 34)
(2, 34)
log prior
[[-1.0171969 ]
 [-0.44880142]]
likelihood 
[[-2.55647005e+00 -7.08733425e-03 -1.63219021e+01 -1.48095565e+01
  -2.48239598e+00 -1.32848651e+01 -1.01943301e+00 -7.10585277e+00
  -1.14330133e+01 -9.82395976e-01 -3.44535894e+00 -5.58116141e+00

ValueError: operands could not be broadcast together with shapes (224,) (2,56) 