In [3]:
# Import package
from urllib.request import urlretrieve

# Import pandas
import pandas as pd

# Assign url of file: url
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/ionosphere/ionosphere.data'

# Save file locally
urlretrieve(url, 'ionosphere-data.csv')

# Read file into a DataFrame and print its head
df = pd.read_csv('ionosphere-data.csv', sep=',')
print(df)

1  0  0.99539  -0.05889  0.85243  0.02306  0.83398  -0.37708      1.1  \
0    1  0  1.00000  -0.18829  0.93035 -0.36156 -0.10868  -0.93597  1.00000   
1    1  0  1.00000  -0.03365  1.00000  0.00485  1.00000  -0.12062  0.88965   
2    1  0  1.00000  -0.45161  1.00000  1.00000  0.71216  -1.00000  0.00000   
3    1  0  1.00000  -0.02401  0.94140  0.06531  0.92106  -0.23255  0.77152   
4    1  0  0.02337  -0.00592 -0.09924 -0.11949 -0.00763  -0.11824  0.14706   
5    1  0  0.97588  -0.10602  0.94601 -0.20800  0.92806  -0.28350  0.85996   
6    0  0  0.00000   0.00000  0.00000  0.00000  1.00000  -1.00000  0.00000   
7    1  0  0.96355  -0.07198  1.00000 -0.14333  1.00000  -0.21313  1.00000   
8    1  0 -0.01864  -0.08459  0.00000  0.00000  0.00000   0.00000  0.11470   
9    1  0  1.00000   0.06655  1.00000 -0.18388  1.00000  -0.27320  1.00000   
10   1  0  1.00000  -0.54210  1.00000 -1.00000  1.00000  -1.00000  1.00000   
11   1  0  1.00000  -0.16316  1.00000 -0.10169  0.99999  -0.15197  1.

In [4]:
# Import numpy
import numpy as np

# Convert to numpy
#df.to_numpy()
temp = df.values
R,C = temp.shape
#print(C)

# Split array into design matrix and labels
ionosphere_labels = temp[:, C-1]
print(ionosphere_labels)



['b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g

In [5]:
import numpy as np
# Remove labels to get design matrix
ionosphere_design_matrix= np.delete(temp, C-1, 1)
print(ionosphere_design_matrix)



[[1 0 1.0 ... -0.06287999999999999 -0.13738 -0.02447]
 [1 0 1.0 ... -0.2418 0.56045 -0.38238]
 [1 0 1.0 ... 1.0 -0.32382 1.0]
 ...
 [1 0 0.94701 ... 0.00442 0.9269700000000001 -0.00577]
 [1 0 0.9060799999999999 ... -0.03757 0.87403 -0.16243]
 [1 0 0.8471 ... -0.06677999999999999 0.85764 -0.06151]]


In [14]:
import Models.kfold_CV_try as cv

# Train test split
xTrain_ion, xTest_ion, yTrain_ion, yTest_ion = cv.split_train_test(ionosphere_design_matrix, ionosphere_labels, 0.2)
# print(xTest_ion); print(xTrain_ion); print(yTest_ion);print(yTrain_ion)


In [25]:
folds = 5 # delete folds later when embedded in function input
# cv_train_data_ion is xTrain_ion split into five chunks
dataset_split_in, cv_train_data_ion,cv_train_label_ion= cv.kfold_cross_validation(xTrain_ion,yTrain_ion,folds)
# print(cv_train_data_ion,cv_train_label_ion)

# the last input for cv.train_validation_split is the number of experiments you are running currently, 5 in total. 
# each experiments is organizing the five chunks from cv_train_data_ion into 4 chunks for training_data_ion and 1 chunk for validate_data_ion, just need to uncomment the line you want to experiment currently. 

#exp1: 
validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,1)

#exp2:
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,2)

#exp3:
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,3)

#exp4:
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,4)

#exp5: 
#validate_data_ion,validate_labels_ion,training_data_ion,training_labels_ion = cv.train_validation_split(cv_train_data_ion,cv_train_label_ion,5)
print(validate_data_ion,validate_labels_ion)
print(validate_data_ion.shape,validate_labels_ion.shape)

[[1 0 0.73523 ... 0.49721000000000004 0.30588000000000004
  0.49831000000000003]
 [1 0 1.0 ... -0.88846 0.29220999999999997 -0.8962100000000001]
 [1 0 0.62121 ... -0.02273 0.17045 -0.41667]
 ...
 [1 0 1.0 ... -0.44505 -0.37432 -0.5331899999999999]
 [1 0 0.64122 ... 0.0 0.17073 0.07317]
 [1 0 0.8941 ... 0.19172 -0.48808 0.05972]] ['g' 'g' 'b' 'g' 'g' 'g' 'g' 'g' 'b' 'b' 'b' 'g' 'g' 'b' 'b' 'b' 'g' 'b'
 'g' 'g' 'g' 'g' 'g' 'g' 'b' 'g' 'b' 'b' 'g' 'b' 'b' 'b' 'b' 'g' 'b' 'g'
 'b' 'g' 'g' 'g' 'g' 'b' 'b' 'g' 'g' 'g' 'b' 'g' 'g' 'g' 'b' 'b' 'g' 'g'
 'g' 'g']
(56, 34) (56,)


In [26]:
import Models.logisticRegression as lr

ionslr1 = lr.Logistic_Regression(0.02,"Ionosphere","binary") # input step size
# params = ionslr1.fit(cv_train_data, cv_train_label, 0.02, 1e-1)
params1 = ionslr1.fit(training_data_ion,training_labels_ion,0.02,1e-1)
#adding a separate comment
# input learning rate and termination conditions

Now fitting Ionosphere
0.59425587954494
0.5784580103373067
0.5631928737952374
0.5484522504666035
0.5342264361744569
0.5205045035018748
0.507274538304543
0.4945238515629254
0.4822391674113059
0.470406788558032
0.4590127405640159
0.44804289659791624
0.4374830843573174
0.427319176854095
0.4175371687247412
0.4081232396559324
0.399063806422743
0.3903455649302364
0.38195552353532397
0.37388102880984964
0.36610978479153927
0.35862986665938157
0.3514297296659656
0.3444982140623847
0.3378245466621106
0.3313983396089488
0.3252095868407395
0.3192486586745675
0.31350629488052134
0.3079735965589838
0.3026420170905262
0.2975033523871859
0.29254973063867146
0.2877736017163712
0.28316772637142856
0.2787251653401397
0.27443926845012123
0.27030366380367427
0.2663122471002233
0.2624591711472942
0.2587388355989627
0.2551458769517784
0.2516751588206638
0.24832176251097973
0.2450809778976911
0.2419482946182023
0.23891939358183198
0.23599013879595626
0.23315656950645544
0.23041489264819273
0.2277614755997298